name: Github actions
run-name: testing out Github actions!
on: [push]
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.1.0
      - name: install deps
        working-directory: my_project
        run: pnpm install
