name: Github actions
run-name: testing out Github actions!
on: [push]
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.1.0

      - name: install deps
        working-directory: my_project
        run: |
          python -m pip install --upgrade pip
          pnpm pip install pytest pytest-playwright
          pnpm pip install "fastapi[standard]"
          pnpm pip install sqlmodel
          pnpm pip install jinja2

      - name: run tests
        working-directory: my_project
        run: pytest test_main.py
      
      - name: Run
        working-directory: my_project
        run: fastapi run

