name: Github actions
run-name: testing out Github actions!
on: [push]
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: install deps
        working-directory: my_project
        run: |
          python -m pip install --upgrade pip
          uv pip install pytest --system
          uv pip install pytest-playwright --system
          uv pip install "fastapi[standard] --system"
          uv pip install sqlmodel --system
          uv pip install jinja2 --system

      - name: run tests
        working-directory: my_project
        run: |
          pytest
      
