name: Github actions
run-name: testing out Github actions!
on: [push]
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: install deps
        working-directory: my_project
        run: |
          python -m pip install --upgrade pip
          uv venv
          uv pip install "fastapi[standard]"
          uv pip install sqlmodel
          uv pip install jinja2

      - name: run tests
        working-directory: my_project
        run: |
          uv venv
          uv pip install pytest
          uv pip install pytest-playwright
          pytest test_main.py
      
