name: Github actions
run-name: testing out Github actions!
on: [push]
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: install deps
        working-directory: my_project
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-playwright
          pip install "fastapi[standard]"
          pip install sqlmodel
          pip install jinja2

      - name: run tests
        working-directory: my_project
        run: pytest test_main.py
      
